#!/usr/bin/env bash

apt-get update

apt-get -y install apache2

## installing mysql
debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
apt-get -y install mysql-server

apt-get -y install mysql-server libapache2-mod-auth-mysql php5-mysql


add-apt-repository ppa:ondrej/php5-5.6
apt-get -y update
apt-get -y install python-software-properties

apt-get update

apt-get -y install php5

apt-get -y install libapache2-mod-php5 php5-mcrypt php5-gd libssh2-php

php5enmod mcrypt
service apache2 restart

/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1
cd /usr/src
apt-get install curl php5-cli
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

cd /


